"""Модель данных: площадки, план, методика, кадры, инциденты

Revision ID: 18e5ce302b0c
Revises: 
Create Date: 2026-09-16 17:39:04.035309+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '18e5ce302b0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_classes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.Enum('equipment', 'person', 'ppe', name='objectcategory', native_enum=False, length=32), nullable=False),
    sa.Column('detector_labels', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('default_confidence_threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_classes'))
    )
    op.create_index(op.f('ix_object_classes_code'), 'object_classes', ['code'], unique=True)
    op.create_table('projects',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('shift_start', sa.Time(), nullable=False),
    sa.Column('shift_end', sa.Time(), nullable=False),
    sa.Column('object_kind', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('admin', 'manager', 'inspector', 'viewer', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('work_types',
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applicable_to', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['work_types.id'], name=op.f('fk_work_types_parent_id_work_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_types'))
    )
    op.create_index(op.f('ix_work_types_code'), 'work_types', ['code'], unique=False)
    op.create_table('cost_rates',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('object_class_id', sa.UUID(), nullable=True),
    sa.Column('rate_per_hour', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_class_id'], ['object_classes.id'], name=op.f('fk_cost_rates_object_class_id_object_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cost_rates_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_rates'))
    )
    op.create_index(op.f('ix_cost_rates_project_id'), 'cost_rates', ['project_id'], unique=False)
    op.create_table('project_settings',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('observation_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('default_confidence_threshold', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('matching_window_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('min_consecutive_misses', sa.Integer(), server_default='3', nullable=False),
    sa.Column('default_sla_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('idle_threshold_minutes', sa.Integer(), server_default='20', nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_settings_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_settings'))
    )
    op.create_table('rule_sets',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_rule_sets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_sets')),
    sa.UniqueConstraint('project_id', 'version', name=op.f('uq_rule_sets_project_id'))
    )
    op.create_index(op.f('ix_rule_sets_project_id'), 'rule_sets', ['project_id'], unique=False)
    op.create_table('zones',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.Enum('normal', 'attention', 'critical', name='zonerisklevel', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_zones_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones'))
    )
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=False)
    op.create_index(op.f('ix_zones_project_id'), 'zones', ['project_id'], unique=False)
    op.create_table('cameras',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('online', 'degraded', 'offline', name='camerastatus', native_enum=False, length=32), nullable=False),
    sa.Column('visibility_percent', sa.Integer(), server_default='100', nullable=False),
    sa.Column('stream_url', sa.Text(), nullable=True),
    sa.Column('archive_url', sa.Text(), nullable=True),
    sa.Column('capture_interval_seconds', sa.Integer(), server_default='30', nullable=False),
    sa.Column('last_frame_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cameras_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_cameras_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_index(op.f('ix_cameras_code'), 'cameras', ['code'], unique=True)
    op.create_index(op.f('ix_cameras_project_id'), 'cameras', ['project_id'], unique=False)
    op.create_table('schedule_tasks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('work_type_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'delayed', 'cancelled', name='scheduletaskstatus', native_enum=False, length=32), nullable=False),
    sa.Column('planned_progress', sa.Float(), nullable=True),
    sa.Column('actual_progress', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_schedule_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], name=op.f('fk_schedule_tasks_work_type_id_work_types'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_schedule_tasks_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_tasks'))
    )
    op.create_index(op.f('ix_schedule_tasks_planned_end'), 'schedule_tasks', ['planned_end'], unique=False)
    op.create_index(op.f('ix_schedule_tasks_planned_start'), 'schedule_tasks', ['planned_start'], unique=False)
    op.create_index(op.f('ix_schedule_tasks_project_id'), 'schedule_tasks', ['project_id'], unique=False)
    op.create_table('work_requirements',
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('work_type_id', sa.UUID(), nullable=False),
    sa.Column('object_class_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('required', 'allowed', 'forbidden', name='rulekind', native_enum=False, length=32), nullable=False),
    sa.Column('min_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_class_id'], ['object_classes.id'], name=op.f('fk_work_requirements_object_class_id_object_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], name=op.f('fk_work_requirements_rule_set_id_rule_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], name=op.f('fk_work_requirements_work_type_id_work_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_requirements')),
    sa.UniqueConstraint('rule_set_id', 'work_type_id', 'object_class_id', name=op.f('uq_work_requirements_rule_set_id'))
    )
    op.create_index(op.f('ix_work_requirements_rule_set_id'), 'work_requirements', ['rule_set_id'], unique=False)
    op.create_index(op.f('ix_work_requirements_work_type_id'), 'work_requirements', ['work_type_id'], unique=False)
    op.create_table('camera_health_events',
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('online', 'degraded', 'offline', name='camerastatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_camera_health_events_camera_id_cameras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera_health_events'))
    )
    op.create_index(op.f('ix_camera_health_events_camera_id'), 'camera_health_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_health_events_started_at'), 'camera_health_events', ['started_at'], unique=False)
    op.create_table('frames',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('thumbnail_key', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('stream', 'upload', 'dataset', name='framesource', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'analyzed', 'failed', name='framestatus', native_enum=False, length=32), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_frames_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_frames_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_frames_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frames'))
    )
    op.create_index('ix_frames_camera_captured', 'frames', ['camera_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_frames_captured_at'), 'frames', ['captured_at'], unique=False)
    op.create_index(op.f('ix_frames_project_id'), 'frames', ['project_id'], unique=False)
    op.create_table('incidents',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('schedule_task_id', sa.UUID(), nullable=True),
    sa.Column('rule_set_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('equipment', 'ppe', 'safety', 'camera', 'progress', 'data', name='incidentcategory', native_enum=False, length=32), nullable=False),
    sa.Column('type', sa.Enum('equipment_missing', 'equipment_insufficient', 'equipment_unexpected', 'ppe_missing', 'camera_offline', 'camera_visibility', 'progress_delay', 'idle_suspected', 'other', name='incidenttype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'in_progress', 'resolved', 'false_positive', name='incidentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='incidentpriority', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('dedup_key', sa.String(length=256), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Enum('low_image_quality', 'wrong_detection', 'not_an_incident', name='rejectreason', native_enum=False, length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_incidents_assigned_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_incidents_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_incidents_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], name=op.f('fk_incidents_rule_set_id_rule_sets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_task_id'], ['schedule_tasks.id'], name=op.f('fk_incidents_schedule_task_id_schedule_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_incidents_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_code'), 'incidents', ['code'], unique=True)
    op.create_index(op.f('ix_incidents_dedup_key'), 'incidents', ['dedup_key'], unique=False)
    op.create_index('ix_incidents_dedup_status', 'incidents', ['dedup_key', 'status'], unique=False)
    op.create_index(op.f('ix_incidents_first_seen_at'), 'incidents', ['first_seen_at'], unique=False)
    op.create_index('ix_incidents_project_first_seen', 'incidents', ['project_id', 'first_seen_at'], unique=False)
    op.create_index(op.f('ix_incidents_project_id'), 'incidents', ['project_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='analysisstatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('detection_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], name=op.f('fk_analysis_runs_frame_id_frames'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    op.create_index(op.f('ix_analysis_runs_frame_id'), 'analysis_runs', ['frame_id'], unique=False)
    op.create_table('incident_events',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('detected', 'updated', 'assigned', 'status_changed', 'commented', 'rejected', 'auto_resolved', name='incidenteventtype', native_enum=False, length=32), nullable=False),
    sa.Column('old_status', sa.Enum('pending', 'confirmed', 'in_progress', 'resolved', 'false_positive', name='incidentstatus', native_enum=False, length=32), nullable=True),
    sa.Column('new_status', sa.Enum('pending', 'confirmed', 'in_progress', 'resolved', 'false_positive', name='incidentstatus', native_enum=False, length=32), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_events_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_incident_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_events'))
    )
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_table('incident_evidence',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('primary', 'before', 'after', 'context', name='evidencekind', native_enum=False, length=32), nullable=False),
    sa.Column('detection_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], name=op.f('fk_incident_evidence_frame_id_frames'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_evidence_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_evidence'))
    )
    op.create_index(op.f('ix_incident_evidence_incident_id'), 'incident_evidence', ['incident_id'], unique=False)
    op.create_table('detections',
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('object_class_id', sa.UUID(), nullable=True),
    sa.Column('raw_label', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('track_id', sa.String(length=64), nullable=True),
    sa.Column('parent_detection_id', sa.UUID(), nullable=True),
    sa.Column('ppe_status', sa.Enum('present', 'not_visible', 'absent', name='ppestatus', native_enum=False, length=32), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_detections_analysis_run_id_analysis_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['frame_id'], ['frames.id'], name=op.f('fk_detections_frame_id_frames'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_class_id'], ['object_classes.id'], name=op.f('fk_detections_object_class_id_object_classes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_detection_id'], ['detections.id'], name=op.f('fk_detections_parent_detection_id_detections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detections'))
    )
    op.create_index(op.f('ix_detections_created_at'), 'detections', ['created_at'], unique=False)
    op.create_index(op.f('ix_detections_frame_id'), 'detections', ['frame_id'], unique=False)
    op.create_index(op.f('ix_detections_track_id'), 'detections', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_track_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_frame_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_created_at'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_incident_evidence_incident_id'), table_name='incident_evidence')
    op.drop_table('incident_evidence')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_analysis_runs_frame_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_project_id'), table_name='incidents')
    op.drop_index('ix_incidents_project_first_seen', table_name='incidents')
    op.drop_index(op.f('ix_incidents_first_seen_at'), table_name='incidents')
    op.drop_index('ix_incidents_dedup_status', table_name='incidents')
    op.drop_index(op.f('ix_incidents_dedup_key'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_code'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_frames_project_id'), table_name='frames')
    op.drop_index(op.f('ix_frames_captured_at'), table_name='frames')
    op.drop_index('ix_frames_camera_captured', table_name='frames')
    op.drop_table('frames')
    op.drop_index(op.f('ix_camera_health_events_started_at'), table_name='camera_health_events')
    op.drop_index(op.f('ix_camera_health_events_camera_id'), table_name='camera_health_events')
    op.drop_table('camera_health_events')
    op.drop_index(op.f('ix_work_requirements_work_type_id'), table_name='work_requirements')
    op.drop_index(op.f('ix_work_requirements_rule_set_id'), table_name='work_requirements')
    op.drop_table('work_requirements')
    op.drop_index(op.f('ix_schedule_tasks_project_id'), table_name='schedule_tasks')
    op.drop_index(op.f('ix_schedule_tasks_planned_start'), table_name='schedule_tasks')
    op.drop_index(op.f('ix_schedule_tasks_planned_end'), table_name='schedule_tasks')
    op.drop_table('schedule_tasks')
    op.drop_index(op.f('ix_cameras_project_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_code'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_zones_project_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_rule_sets_project_id'), table_name='rule_sets')
    op.drop_table('rule_sets')
    op.drop_table('project_settings')
    op.drop_index(op.f('ix_cost_rates_project_id'), table_name='cost_rates')
    op.drop_table('cost_rates')
    op.drop_index(op.f('ix_work_types_code'), table_name='work_types')
    op.drop_table('work_types')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_object_classes_code'), table_name='object_classes')
    op.drop_table('object_classes')
    # ### end Alembic commands ###
